Repository atlp-rwanda/e-commerce-lydia-32-fn, pull requests merged in 2024-07, with the labels that each got.

#6 Have eslint and Git Pre-commit hooks running before every commit
  .env
  .gitignore
  .husky/pre-commit
  eslint.config.js
  package.json
  vite.config.ts
Labels: Ready

#8 Users should be able to Login with Email and Password
  .github/PULL_REQUEST_TEMPLATE.MD
  package-lock.json
  package.json
  src/App.tsx
  src/Components/footer.tsx
  src/Components/navbar.tsx
  src/assets/Background.jpg
  src/assets/Morris.jpeg
  src/assets/bahati.jpeg
  src/assets/depot.jpg
  src/assets/derrick.png
  src/assets/didas.png
  src/assets/lydia.png
  src/assets/martial.jpeg
  src/assets/pacifique.png
  src/assets/robert.jpeg
  src/assets/rodrigue.jpeg
  src/layouts/MainLayout.tsx
  src/pages/AboutUs.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/ourTeam.tsx
  src/slices/authSlice/authApiSlice.tsx
  src/store.tsx
  tailwind.config.js
  yarn.lock
Labels: Ready for merge

#9 ft-187570816 Login by google
  .husky/pre-commit
  src/Components/Login.tsx
  src/layouts/MainLayout.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/ourTeam.tsx
  src/slices/productSlice/productApiSlice.tsx
  yarn.lock
Labels: Ready for merge

#15 ft-homePageDesign
  src/Components/product.tsx
  src/assets/chair.png
  src/assets/hero.png
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/slices/authSlice.tsx
Labels: Ready for peer review

#10 Ft logout
  src/Components/navbar.tsx
  src/slices/authSlice/authApiSlice.tsx
  vite.config.ts
Labels: Ready for merge, Ready for peer review

#7 ft Requesting a reset password due to a forgotten password front-end
  .gitignore
  src/App.tsx
  src/Components/ForgotPassword.tsx
  src/Components/Notification.tsx
  src/Components/ResetPassword.tsx
  src/pages/ForgotPassword.tsx
  src/pages/ResetPassword.tsx
Labels: Ready for merge

#14 ft: Add 404 not found page
  .env
  src/App.tsx
  src/pages/Login.tsx
  src/pages/NotFoundPage.tsx
  vite.config.ts
Labels: Ready for merge

#17 Fix seller2fa login
  src/Components/navbar.tsx
  src/pages/Login.tsx
  src/slices/authSlice/authApiSlice.tsx
  src/store.tsx
Labels: Ready for merge

#16 Ft register and verify email 187570815
  .env
  .vite/deps/@react-oauth_google.js
  .vite/deps/@react-oauth_google.js.map
  .vite/deps/@reduxjs_toolkit.js
  .vite/deps/@reduxjs_toolkit.js.map
  .vite/deps/@reduxjs_toolkit_query_react.js
  .vite/deps/@reduxjs_toolkit_query_react.js.map
  .vite/deps/_metadata.json
  .vite/deps/chunk-EWTE5DHJ.js
  .vite/deps/chunk-EWTE5DHJ.js.map
  .vite/deps/chunk-J4KOQHYD.js
  .vite/deps/chunk-J4KOQHYD.js.map
  .vite/deps/chunk-SD42HLFO.js
  .vite/deps/chunk-SD42HLFO.js.map
  .vite/deps/chunk-SZF5K3LI.js
  .vite/deps/chunk-SZF5K3LI.js.map
  .vite/deps/chunk-UHINIFCJ.js
  .vite/deps/chunk-UHINIFCJ.js.map
  .vite/deps/chunk-W4EHDCLL.js
  .vite/deps/chunk-W4EHDCLL.js.map
  .vite/deps/package.json
  .vite/deps/react-dom_client.js
  .vite/deps/react-dom_client.js.map
  .vite/deps/react-hot-toast.js
  .vite/deps/react-hot-toast.js.map
  .vite/deps/react-icons_fa.js
  .vite/deps/react-icons_fa.js.map
  .vite/deps/react-icons_fc.js
  .vite/deps/react-icons_fc.js.map
  .vite/deps/react-modal.js
  .vite/deps/react-modal.js.map
  .vite/deps/react-redux.js
  .vite/deps/react-redux.js.map
  .vite/deps/react-router-dom.js
  .vite/deps/react-router-dom.js.map
  .vite/deps/react-spinners_DotLoader.js
  .vite/deps/react-spinners_DotLoader.js.map
  .vite/deps/react-toastify.js
  .vite/deps/react-toastify.js.map
  .vite/deps/react.js
  .vite/deps/react.js.map
  .vite/deps/react_jsx-dev-runtime.js
  .vite/deps/react_jsx-dev-runtime.js.map
  package-lock.json
  package.json
  src/App.tsx
  src/layouts/MainLayout.tsx
  src/main.tsx
  src/pages/ForgotPassword.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/pages/ResetPassword.tsx
  src/pages/verified.tsx
  src/pages/verifyFailed.tsx
  src/slices/authSlice.tsx
  src/slices/authSlice/authApiSlice.tsx
  src/slices/roleSlice/requestRoleSlice.tsx
  src/slices/roleSlice/requestroleApiSlice.tsx
  src/store.tsx
Labels: Ready for merge

#24 buyer is able to add items to cart
  .gitignore
  package.json
  src/App.tsx
  src/Components/product.tsx
  src/pages/Cart.tsx
  src/pages/SingleProduct.tsx
  src/slices/apiSlice.tsx
  src/slices/cartSlice/cartApiSlice.tsx
  src/slices/cartSlice/cartSlice.tsx
  src/slices/roleSlice/requestRoleSlice.tsx
  src/slices/roleSlice/requestroleApiSlice.tsx
  src/store.tsx
  vite.config.ts
  yarn.lock
Labels: Ready for peer review

#23 view user profile
  public/Background.jpg
  src/App.tsx
  src/Components/navbar.tsx
  src/assets/user-solid.svg
  src/pages/Profile.tsx
  src/slices/authSlice/authApiSlice.tsx
  src/slices/authSlice/authSlice.tsx
Labels: Ready for peer review

#22 ft-187570826 Admin Dashboard Feature
  package.json
  src/App.tsx
  src/Components/admin/Header.tsx
  src/Components/admin/MainContent.tsx
  src/Components/admin/Permissions.tsx
  src/Components/admin/RecentOrders.tsx
  src/Components/admin/Roles.tsx
  src/Components/admin/Sidebar.tsx
  src/Components/admin/Statistics.tsx
  src/Components/admin/Users.tsx
  src/Components/admin/WebsiteStatistics.tsx
  src/Components/admin/useDataFetchQueue.tsx
  src/Components/navbar.tsx
  src/layouts/MainLayout.tsx
  src/pages/Login.tsx
  src/pages/admin/AdminAssignPermiToRole.tsx
  src/pages/admin/AdminAssignRoleToUser.tsx
  src/pages/admin/AdminCreatePermission.tsx
  src/pages/admin/AdminCreateRole.tsx
  src/pages/admin/AdminDashboard.tsx
  src/pages/admin/AdminDeletePermiFromRole.tsx
  src/pages/admin/AdminEditRole.tsx
  src/pages/admin/AdminPageOnly.tsx
  src/slices/orderSlice/orderApiSlice.tsx
  src/slices/orderSlice/orderSlice.tsx
  src/slices/permissionSlice/permissionApiSlice.tsx
  src/slices/permissionSlice/permissionSlice.tsx
  src/slices/roleSlice/requestRoleSlice.tsx
  src/slices/roleSlice/requestroleApiSlice.tsx
  src/slices/usersSlice/userApiSlice.tsx
  src/slices/usersSlice/userSlice.tsx
  src/store.tsx
  yarn.lock
Labels: Ready for peer review

#20 ft-187570820-PasswordExpirationPrompt
  src/App.tsx
  src/Components/EmptyCart.tsx
  src/Components/navbar.tsx
  src/pages/Cart.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/SingleProduct.tsx
  src/pages/changePassword.tsx
  src/pages/updatePassword.tsx
  src/slices/authSlice/authApiSlice.tsx
  src/slices/cartSlice/cartApiSlice.tsx
Labels: Ready for peer review

#25 Ft buyer should be able to view their cart#187570835
  src/Components/ConfirmationDialog.tsx
  src/pages/Cart.tsx
  src/pages/SingleProduct.tsx
Labels: Ready for peer review

#28 Fix deployed login error
  src/pages/Cart.tsx
  src/pages/Login.tsx
Labels: Ready for merge

#29 Ft buyer should be able to view their cart#187570835
  src/pages/Cart.tsx
  src/pages/SingleProduct.tsx
Labels: Ready for merge

#26 Seller can add a new product
  package.json
  src/App.tsx
  src/Components/Notification.tsx
  src/Components/seller/CategoriesPieChart.tsx
  src/Components/seller/Notification.tsx
  src/Components/seller/pieChart.tsx
  src/Components/seller/sellerDashboardNavbar.tsx
  src/Components/seller/sellerSidebar.tsx
  src/assets/analyticsIcon.png
  src/assets/dashboardIcon.png
  src/assets/dashboardIcon.svg
  src/assets/hamburgerIcon.png
  src/assets/hamburgerIcon.svg
  src/assets/logoutIcon.png
  src/assets/newProductIcon.png
  src/assets/notification.png
  src/assets/notification.svg
  src/assets/notificationIcon.svg
  src/assets/personIcon.png
  src/assets/productIcon.png
  src/assets/profileIcon.svg
  src/assets/reviewIcon.png
  src/layouts/MainLayout.tsx
  src/layouts/sellerDashboardLayout.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/pages/seller/AddProduct.tsx
  src/pages/seller/GeneralAnalysis.tsx
  src/pages/seller/NotificationBar.tsx
  src/pages/seller/SellerPageOnly.tsx
  src/slices/apiSlice.tsx
  src/slices/notificationSlice/notificationApiSlice.tsx
  src/slices/notificationSlice/notificationSlice.tsx
  src/slices/productSlice/productApiSlice.tsx
  src/slices/sellerSlice/sellerProductSlice.tsx
  src/slices/sellerSlice/sellerProductsApiSlice.tsx
  src/store.tsx
  tailwind.config.js
Labels: Ready for merge

#21 Seller can view single item and all Items with pagination
  coverage/lcov-report/index.html
  index.html
  package.json
  src/App.tsx
  src/Components/SellerProductCard.tsx
  src/layouts/SellerLayout.tsx
  src/pages/SellerAllProductsPage.tsx
  src/pages/SellerSingleProductPage.tsx
  src/slices/productSlice/productApiSlice.tsx
  src/slices/productSlice/singleApiSlice.tsx
Labels: Ready for merge

#33 ft seller should be able to delete a product
  src/Components/SellerProductCard.tsx
  src/pages/SellerAllProductsPage.tsx
  src/pages/SellerSingleProductPage.tsx
  src/slices/productSlice/productApiSlice.tsx
  src/slices/sellerSlice/sellerProductsApiSlice.tsx
  src/slices/sellerSlice/singlerSellerProductsApiSlice.tsx
Labels: Ready for merge

#35 Implementing User Wishlist feature
  src/App.tsx
  src/Components/navbar.tsx
  src/Components/wishlistEmpty.tsx
  src/assets/CLOSE-ICON.png
  src/assets/wishlistIcon.png
  src/assets/wishlistIcon.svg
  src/pages/SingleProduct.tsx
  src/pages/wishlist.tsx
  src/slices/apiSlice.tsx
  src/slices/wishlistSlice/wishlistSlice.tsx
  src/slices/wishlistSlice/wishlistSliceApi.tsx
  src/store.tsx
Labels: Ready for merge

#36 Ft seller update product
  package.json
  src/Components/UpdateProductDialog.tsx
  src/hooks.ts
  src/pages/SellerSingleProductPage.tsx
  src/pages/SingleProduct.tsx
  src/slices/productSlice/updateProductSlice.ts
  src/slices/sellerSlice/editSlice.ts
  src/utils/api.ts
Labels: Ready for merge, Ready for peer review

#31 Ft-buyerShouldBeAbleToTrackTheirOrderStatus#187570844
  package.json
  src/App.tsx
  src/Components/navbar.tsx
  src/pages/Profile.tsx
  src/pages/customerSupport.tsx
  src/pages/order/orderDetail.tsx
  src/pages/order/orderHistory.tsx
  src/slices/orderSlice/orderApiSlice.tsx
  src/slices/orderSlice/orderSlice.tsx
Labels: Ready for merge

#32 Pyament with stripe implementation
  .gitignore
  package.json
  src/App.tsx
  src/Components/navbar.tsx
  src/Components/seller/Notification.tsx
  src/Components/seller/sellerDashboardNavbar.tsx
  src/pages/Cart.tsx
  src/pages/Checkout.tsx
  src/pages/OrderConfirmation.tsx
  src/pages/PaymentSuccess.tsx
  src/pages/PyamentErroPage.tsx
  src/pages/SingleProduct.tsx
  src/pages/seller/GeneralAnalysis.tsx
  src/pages/seller/NotificationBar.tsx
  src/slices/orderSlice/buyerOrderApiSlice.tsx
  src/slices/orderSlice/orderApiSlice.tsx
  src/slices/paymentSlice/paymentApiSlice.tsx
  src/slices/paymentSlice/paymentSlice.tsx
  tsconfig.app.json
  yarn.lock
Labels: Ready for merge

#39 Fix Single Seller page showing user navbar
  src/App.tsx
  src/pages/SellerSingleProductPage.tsx
Labels: Ready for merge

#38 mar all notification as read
  package.json
  src/Components/NotificationIcon.tsx
  src/Components/navbar.tsx
  src/Components/seller/Notification.tsx
  src/Components/seller/sellerDashboardNavbar.tsx
  src/pages/seller/AddProduct.tsx
  src/pages/seller/NotificationBar.tsx
  src/slices/notificationSlice/notificationApiSlice.tsx
  src/slices/notificationSlice/notificationSlice.tsx
  yarn.lock
Labels: Ready for merge, Ready for peer review

#37 ft(seller-checkout): Have a seller be able to checkout
  src/Components/navbar.tsx
  src/Components/seller/sellerSidebar.tsx
  src/assets/home.png
  src/assets/icons8-home.gif
  src/pages/SingleProduct.tsx
  src/pages/seller/AddProduct.tsx
  src/pages/wishlist.tsx
Labels: Ready for merge

#40 Chat app 187570830
  package.json
  src/App.tsx
  src/Components/navbar.tsx
  src/contexts/notificationContext.tsx
  src/layouts/MainLayout.tsx
  src/layouts/SellerLayout.tsx
  src/pages/Chat.tsx
  src/pages/Home.tsx
  src/pages/order/orderDetail.tsx
  src/pages/seller/NotificationBar.tsx
  src/slices/notificationSlice/notificationSlice.tsx
  src/utils/notifications/notificationSound.wav
  src/utils/notifyUsers.ts
  test.js
  yarn.lock
Labels: Ready for merge

#42 ft/seller-statistics-timeframe#187570861
  package.json
  src/Components/seller/sellerDashboardNavbar.tsx
  src/Components/seller/sellerSidebar.tsx
  src/pages/seller/GeneralAnalysis.tsx
  src/pages/seller/sellerStats.tsx
  src/slices/orderSlice/orderApiSlice.tsx
  src/slices/orderSlice/orderSlice.tsx
  tailwind.config.js
  yarn.lock
Labels: Ready for merge

#41 New Notification Toast
  src/pages/seller/NotificationBar.tsx
  src/slices/notificationSlice/notificationSlice.tsx
  yarn.lock
Labels: Ready for merge

#43 Fix logout user server error
  package.json
  src/Components/navbar.tsx
  src/hooks/useCheckAuth.ts
  src/slices/authSlice/authSlice.tsx
  src/utils/cryptoUtils.ts
Labels: Ready for merge
